---
- name: Create a directory for compose project
  ansible.builtin.file:
    path: "/opt/services/proxy_manager"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Template of compose file
  ansible.builtin.template:
    src: "templates/proxy_manager.j2"
    dest: "/opt/services/proxy_manager/compose.yaml"
    mode: '0755'
    owner: root
    group: root

- name: Run docker container
  ansible.builtin.command:
    cmd: "docker compose -f /opt/services/proxy_manager/compose.yaml up -d"
