---
- name: Create a directory for compose project
  ansible.builtin.file:
    path: "/opt/services/{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Template of compose file
  ansible.builtin.template:
    src: "templates/{{ item }}.j2"
    dest: "/opt/services/{{ item }}/compose.yaml"
    owner: root
    group: root
    mode: '0755'

- name: Run docker container
  ansible.builtin.command:
    cmd: "docker compose -f /opt/services/{{ item }}/compose.yaml up  -d"
