---
- name: Update & upgrade packages
  ansible.builtin.import_tasks: apt.yaml

- name: SSH Setup
  ansible.builtin.import_tasks: ssh.yaml

- name: UFW Setup
  ansible.builtin.import_tasks: ufw.yaml

- name: Docker Setup
  ansible.builtin.import_tasks: docker.yaml
