---
- name: Setup ssh service
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item }}"
    line: "{{ item }} no"
  loop:
    - 'PasswordAuthentication'
    - 'ChallengeResponseAuthentication'

- name: Restart ssh service
  ansible.builtin.systemd_service:
    name: ssh
    state: restarted
    enabled: true
