---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Start ufw service
  ansible.builtin.systemd_service:
    name: ufw
    state: started
    enabled: true

- name: Reset ufw
  community.general.ufw:
    state: reset

- name: Common setup ufw
  ansible.builtin.shell:
    cmd: |
      ufw default deny incoming
      ufw default allow outgoing
      ufw allow 22
      ufw allow 80
      ufw allow 81
      ufw allow 443
      ufw allow 8443
      ufw allow 8080
      ufw allow 8081
      ufw allow 1080
      ufw allow 2053
      ufw allow 2083
      ufw allow 19284

- name: Enable ufw
  community.general.ufw:
    state: enabled
